image:
- Ubuntu2004
- macOs
- Visual Studio 2019

configuration: Release
platform: x64
clone_depth: 1

for:
-
  matrix:
    only:
      - image: Ubuntu2004
  environment:
    CMAKE_PREFIX_PATH: /home/appveyor/Qt/5.15/gcc_64
  install:
    - sudo apt -qq update
    - sudo apt install -y mesa-common-dev libglu1-mesa-dev
  after_build:
  - strip screenshotgun
  # before_deploy:
  # - zip screenshotgun_linux.zip screenshotgun
  artifacts:
  - path: screenshotgun
    name: screenshotgun
-
  matrix:
    only:
      - image: macOs
  environment:
    CMAKE_PREFIX_PATH: /Users/appveyor/Qt/5.15/clang_64
  after_build:
  - strip screenshotgun.app/Contents/MacOS/screenshotgun
  # before_deploy:
  # - zip -r screenshotgun_macos.zip screenshotgun.app
  artifacts:
  - path: screenshotgun.app
    name: screenshotgun
    type: zip
-
  matrix:
    only:
      - image: Visual Studio 2019
  environment:
    CMAKE_PREFIX_PATH: C:\Qt\5.15.2\msvc2019_64
  # before_deploy:
  # - 7z a -tzip screenshotgun_windows.zip Release\screenshotgun.exe
  artifacts:
  - path: Release\screenshotgun.exe
    name: screenshotgun
    type: zip

build_script:
- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake --build . --config Release

deploy:
- provider: GitHub
  auth_token:
    secure: 0GaldFB6iA6/Op54kN+749ZPJ09jc458c74JxmaUm5vVsu7v56J4JZRmwSwqrmff
  artifact: screenshotgun
  on:
    APPVEYOR_REPO_TAG: true
