language: cpp
os: linux
dist: xenial
services:
  - docker

before_install:
  - sudo apt-get update
  - openssl aes-256-cbc -K $encrypted_55f6cc107eaa_key -iv $encrypted_55f6cc107eaa_iv
    -in deploy/data/deploy.tar.enc -out deploy/data/deploy.tar -d
  - tar xvf deploy/data/deploy.tar

install:
  - sudo apt-get install qtbase5-dev qtbase5-private-dev

script:
  # - mkdir build && cd build
  # - cmake -DCMAKE_BUILD_TYPE=Release ..
  # - cmake --build .
  # - strip screenshotgun
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
