language: cpp
os: linux
dist: xenial

before_install:
  - openssl aes-256-cbc -K $encrypted_55f6cc107eaa_key -iv $encrypted_55f6cc107eaa_iv -in deploy/arch/aur.enc -out deploy/arch/aur -d
  # Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo systemctl start docker

install:
  - sudo apt-get install qtbase5-dev qtbase5-private-dev

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - strip screenshotgun
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
