language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      services:
        - docker
    - os: osx
      addons:
        homebrew:
          packages:
          - qt
          update: true
      cache:
        directories:
        - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup

before_install:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/before_install.sh
install:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/install.sh
script:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/script.sh
deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/deploy.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
