language: cpp
os: linux
dist: xenial
services:
  - docker

before_install:
  - sudo apt-get update
  - openssl aes-256-cbc -K $encrypted_55f6cc107eaa_key -iv $encrypted_55f6cc107eaa_iv -in deploy/arch/aur.enc -out deploy/arch/aur -d

install:
  - sudo apt-get install qtbase5-dev qtbase5-private-dev

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - strip screenshotgun
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG
  on:
    tags: true
